language: "en-US"
early_access: false
reviews:
    profile: "chill"
    high_level_summary: true
    poem: false
    review_status: false
    commit_status: false
    changed_files_summary: false
    sequence_diagrams: false
