export const actionButton = "div > button[aria-label='Actions']";
export const applicationNameInput = "input[name=name]";
export const applicationDescriptionInput = "input[name=description]";
export const applicationBusinessServiceSelect = "[placeholder='Select a business service']";
export const applicationTagsSelect = "[placeholder='Select a tag(s)']";
export const applicationCommentInput = "textarea[name=comments]";
export const businessColumnSelector = "td[data-label='Business service']";
export const csvFileName = "File name";
export const closeForm = "button[aria-label='close']";
export const dependenciesDropdownBtn = "button[aria-label='Options menu']";
export const date = "Date";
export const editButton = "div[class='pf-c-inline-edit__action pf-m-enable-editable'] > button";
export const importStatus = "Status";
export const selectBox = "input[type=checkbox]";
export const tags = "span";
export const user = "User";
