export const applicationNameInput = "input[name=name]";
export const applicationDescriptionInput = "input[name=description]";
export const applicationBusinessServiceSelect = "[placeholder='Select a business service']";
export const applicationTagsSelect = "[placeholder='Select a tag(s)']";
export const applicationCommentInput = "textarea[name=comments]";
export const editButton = "div[class='pf-c-inline-edit__action pf-m-enable-editable'] > button";
export const actionButton = "div > button[aria-label='Actions']";
export const selectBox = "input[type=checkbox]";
export const stakeholderSelect = "input[placeholder='Select stakeholder(s)']";
export const stakeholdergroupsSelect = "input[placeholder='Select stakeholder group(s)']";
export const questionBlock = "div[cy-data='question']";
export const radioInput = "input[type='radio']";
export const selectInput = "input[placeholder='Select']";
export const criticalityInput = "input[name='criticality']";
export const priorityInput = "input[name='priority']";
export const reviewColumnSelector = "td[data-label='Review']";
export const assessmentColumnSelector = "td[data-label='Assessment']";
