export const itemsPerPageToggleButton = "button[aria-label='Items per page']";
export const submitButton = "button[aria-label=submit]";
export const cancelButton = "button[aria-label=cancel]";
export const closeButton = "button[aria-label=Close]";
export const confirmButton = "button[aria-label=confirm]";
export const editButton = "button[aria-label=edit]";
export const deleteButton = "button[aria-label=delete]";
export const controlsForm = "form.pf-c-form";
export const itemsPerPageMenu = "div.pf-c-options-menu";
export const itemsPerPageMenuOptions = "ul[aria-labelledby='pagination-options-menu-toggle']";
export const expandRow = "button[aria-label=Details]";
export const successAlertMessage = "div[aria-label='Success Alert']";
export const duplicateNameWarning = "div[aria-label='Danger Alert']";
export const nameHelper = "div[id=name-helper]";
export const descriptionHelper = "div[id=description-helper]";
