export const itemsPerPageToggleButton = "button[aria-label='Items per page']";
export const submitButton = "button[aria-label=submit]";
export const cancelButton = "button[aria-label=cancel]";
export const closeButton = "button[aria-label=Close]";
export const confirmButton = "button[aria-label=confirm]";
export const editButton = "button[aria-label=edit]";
export const deleteButton = "button[aria-label=delete]";
export const removeButton = "button[aria-label='Remove']";
export const clearAllButton = "button[aria-label='Clear all']";
export const controlsForm = "form.pf-c-form";
export const itemsPerPageMenu = "div.pf-c-options-menu";
export const itemsPerPageMenuOptions = "ul[aria-labelledby='pagination-id-toggle']";
export const expandRow = "button[aria-label=Details]";
export const successAlertMessage = "div[aria-label='Success Alert']";
export const duplicateNameWarning = "div[aria-label='Danger Alert']";
export const appTable = "table[aria-label='main-table']";
export const nameHelper = "div[id=name-helper]";
export const descriptionHelper = "div[id=description-helper]";
export const filterToggleButton = "div.pf-c-dropdown > button.pf-c-dropdown__toggle";
export const filterInput = "input[aria-label='filter-text']";
export const searchButton = "button[aria-label=search]";
export const nextPageButton = "button[aria-label='Go to next page']";
export const prevPageButton = "button[aria-label='Go to previous page']";
export const lastPageButton = "button[aria-label='Go to last page']";
export const firstPageButton = "button[aria-label='Go to first page']";
export const pageNumInput = "input[aria-label='Current page']";
