export enum CustomMigrationTargetView {
    createSubmitButton = "button[id='identity-form-submit']:contains('Create')",
    editSubmitButton = "button[id='identity-form-submit']:contains('Save')",
    actionsButton = "button[aria-label=Actions]",
    nameInput = "#name",
    nameHelper = "#name-helper",
    descriptionInput = "#description",
    imageInput = "#custom-migration-target-upload-image-filename",
    imageHelper = "#custom-migration-target-upload-image-helper",
    ruleInput = "div.pf-c-multiple-file-upload > input[accept='.xml']",
    ruleHelper = "div[aria-label='Danger Alert']",
    ruleFilesToggle = "button[aria-expanded='true']",
    takeMeThereNotification = "Take me there",
    repositoryTypeDropdown = "#repo-type-select-toggle",
    repositoryUrl = "#sourceRepository",
    repositoryUrlHelper = "#sourceRepository-helper",
    branch = "#branch",
    rootPath = "#rootPath",
    credentialsDropdown = "#associated-credentials-select-toggle",
    retrieveFromARepositoryRadio = "#repository",
    dragButton = "#drag-button",
}
