export const addUserButton = "button[data-testid='add-user']";
export const saveUserButton = "button[data-testid='user-creation-save']";
export const createPasswordButton = "button[data-testid='no-credentials-empty-action']";
export const passwordInput = "#password";
export const passwordConfirm = "#passwordConfirmation";
export const kebabToogleButton = 'button[aria-label="Kebab toggle"]';
export const modalConfirmButton = "#modal-confirm";
export const tempPasswordToggle = "#temporaryPassword";
export const assignRoleButton = 'button[data-testid="add-role-mapping-button"]';
export const filterTypeDropdown = 'button[data-testid="filter-type-dropdown"]';
export const assignButton = 'button[data-testid="assign"]';
export const checkBox = "input";
